### ISSUE TITLE
Apply PSR-2 code standard

### ISSUE THREAD

**Issue by harikt** [Tuxion/DoctrineRest#9]
Hey @Beanow , @Avaq ,

Humble request please guys can we follow the PSR-2 for open-source projects?

I am not here to make a controversial stuff. If you love please consider it.

Thank you.

**Comment by Beanow** [comment]
Currently our work environment is not set up to follow PSR-2. I will have to look into refactoring and enforcement tools for PSR-2. For DoctrineRest this is an enhancement for later.

**Comment by harikt** [comment]
@Beanow look into http://cs.sensiolabs.org .

**Comment by Beanow** [comment]
:smiley: https://github.com/benmatselby/sublime-phpcs also looks interesting from that page.

**Comment by harikt** [comment]
great! . It will be nice. 

Thank you.

**Comment by harikt** [comment]
There is also PHP_Codesniffer .
